name: Release

on:
  workflow_call:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Create release
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: executables
          path: ./artifacts

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/*
